# Generated by Django 2.2.7 on 2020-04-13 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_money_grant', models.FloatField(default=0.0)),
                ('maxTurns', models.IntegerField(default=99)),
                ('current_turn', models.IntegerField(default=0)),
                ('gamemaster', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='gamemaster', to=settings.AUTH_USER_MODEL)),
                ('players', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='players', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
