# Generated by Django 2.2.7 on 2020-04-13 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinstance',
            name='players',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='players', to=settings.AUTH_USER_MODEL),
        ),
    ]
