# Generated by Django 2.2.7 on 2020-04-22 07:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game_management', '0002_auto_20200413_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinstance',
            name='maxTurns',
            field=models.IntegerField(default=15),
        ),
        migrations.RemoveField(
            model_name='gameinstance',
            name='players',
        ),
        migrations.AddField(
            model_name='gameinstance',
            name='players',
            field=models.ManyToManyField(related_name='players', to=settings.AUTH_USER_MODEL),
        ),
    ]
