# Generated by Django 2.2.7 on 2020-04-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20200413_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='risk_rating',
            field=models.TextField(default='low'),
        ),
        migrations.AddField(
            model_name='stock',
            name='trend_value',
            field=models.TextField(default='stable'),
        ),
    ]
